# Generated by Django 4.0.3 on 2022-03-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254)),
                ('tfono', models.CharField(max_length=10, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPedido', models.IntegerField()),
                ('fechaPedido', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='seccion',
            field=models.CharField(default=2, max_length=20, verbose_name='Sección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
