# Generated by Django 4.0.3 on 2022-03-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_cliente_pedido_articulo_precio_articulo_seccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
