# Generated by Django 4.0.3 on 2022-03-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionPedidos', '0003_delete_articulo_delete_cliente_delete_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('seccion', models.CharField(max_length=20, verbose_name='Sección')),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254)),
                ('tfono', models.CharField(max_length=10, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPedido', models.IntegerField()),
                ('fechaPedido', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
